minVersion: '2.0.0'
github:
  owner: getsentry
  repo: rrweb
changelog:
  policy: auto
preReleaseCommand: bash scripts/craft-pre-release.sh
requireNames:
  - /^sentry-rrweb-snapshot-.*\.tgz$/
  - /^sentry-rrweb-player-.*\.tgz$/
  - /^sentry-rrweb-packer-.*\.tgz$/
  - /^sentry-rrweb-types-.*\.tgz$/
  - /^sentry-rrweb-(?!worker-).*\.tgz$/
  - /^sentry-rrdom-.*\.tgz$/
targets:
  - name: github
    includeNames: /^sentry-.*.tgz$/
  - name: npm
    includeNames: /^sentry-.*.tgz$/
